Fine tune Detr
In colab, you need to use
torch==1.8.0 torchvision==0.9.0

Error:
Got error "cannot import name '_new_empty_tensor' from 'torchvision.ops'" in colab

Solution:
https://github.com/facebookresearch/detectron2/issues/3191